// sub-react/react-app/src/App.js
import Home from "./components/Home"
import About from "./components/About"
import {Routes, Route, Link } from "react-router-dom";

function App(props) {
  return (
    <div className="App">
      <header className="App-header">
        <h2>React应用</h2>
        <div>
          <ul>
            <li><h3>主应用传递--{props.msg}</h3></li>
            <li><Link to="/">主页面</Link></li>
            <li><Link to="/about">About面</Link></li>
          </ul>
          <Routes>
            <Route path="/" element={<Home></Home>}></Route>
            <Route path="/about" element={<About></About>}></Route>
          </Routes>
        </div>
      </header>
    </div>
  );
}

export default App;

// sub-vue/vue-app/src/App.vue
<template>
  <div>
    <h2>V3微应用</h2>
    <ul>
      <li><h3>主应用传递---{{msg}}</h3></li>
      <li><router-link to="/">Home页面</router-link></li>
      <li><router-link to="about">About页面</router-link></li>
    </ul>
    <router-view></router-view>
  </div>
</template>

<script>


export default {
  name: 'App',
  components: {
  },
  props: ['msg'],
  setup() {
    return {
      list_v3: {
        id: 90
      }
    }
  },
  data() {
    return {
      a_v3: 100
    }
  }
}
</script>

<style>
  ul {
    margin: 20px auto;
  }
</style>
